name: Docker Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build yftp-server
      run: |
        docker build ./yftp-server -t sneakypanda64/atlasservers:hyperion.yftp --progress=plain --platform=linux/arm64/v8
    - name: docker pushing yftp-server
      run: |
        docker push sneakypanda64/atlasservers:hyperion.yftp
    - name: docker build performance-server
      run: |
        docker build ./performance-server -t sneakypanda64/atlasservers:hyperion.performance --progress=plain
    - name: docker pushing performance-server
      run: |
        docker push sneakypanda64/atlasservers:hyperion.performance
