on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: YFTP Server - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./yftp-server
          platforms: linux/arm/v8
          push: true
          tags: sneakypanda64/atlasservers:hyperion.yftp
      -
        name: Performance Server - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./performance-server
          platforms: linux/amd64
          push: true
          tags: sneakypanda64/atlasservers:hyperion.performance
